---
- name: CONFIGURATION EIGRP from TXT
  hosts: R1
  gather_facts: true
  connection: local

  tasks:
  
   - name: EIGRP Configuration
     ios_config:
      authorize: yes
      auth_pass: cisco
      src: "config/R1_loopback.txt"